permalink:           pretty

# Setup
title:               Ökumenischer Arbeitskreis Asyl Möglingen
tagline:             A responsive blog theme that illustrates reading progress. Suited for continous reading.
